// wgo - Go port of WireViz.
//
// Copyright (C) 2026 the wgo contributors.
// Based on WireViz (https://github.com/wireviz/WireViz), copyright its
// respective contributors.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Package parser loads a WireViz harness YAML document with PyYAML-compatible
// semantics (ordered mappings, merge keys, scalar resolution) and drives the
// parsing pipeline defined in wireviz.py.
package parser

import (
	"fmt"
	"strings"

	harnesspkg "github.com/dmundt/wgo/pkg/harness"
	"github.com/dmundt/wgo/pkg/utils"
)

func processConnections(connectionSets []any, templateSeparator string, templateConnectors, templateCables *utils.OrderedMap, h *harnesspkg.Harness) {
	designatorsAndTemplates := map[string]string{}
	autogeneratedDesignators := map[string]int{}
	expectedType := ""

	resolveDesignator := func(inp, sep string) (string, string) {
		if strings.Contains(inp, sep) {
			if strings.Count(inp, sep) > 1 {
				panic(fmt.Errorf("%s - Found more than one separator (%s)", inp, sep))
			}
			parts := strings.SplitN(inp, sep, 2)
			template, designator := parts[0], parts[1]
			if designator == "" {
				autogeneratedDesignators[template]++
				designator = fmt.Sprintf("__%s_%d", template, autogeneratedDesignators[template])
			}
			if t, ok := designatorsAndTemplates[designator]; ok {
				if t != template {
					panic(fmt.Errorf("Trying to redefine %s from %s to %s", designator, t, template))
				}
			} else {
				designatorsAndTemplates[designator] = template
			}
			return template, designator
		}
		template, designator := inp, inp
		if _, ok := designatorsAndTemplates[designator]; !ok {
			designatorsAndTemplates[designator] = template
		}
		return template, designator
	}

	checkType := func(designator, template, actualType string) {
		if expectedType == "" {
			expectedType = actualType
		}
		if actualType != expectedType {
			panic(fmt.Errorf("Expected %s, but \"%s\" (\"%s\") is %s", expectedType, designator, template, actualType))
		}
	}

	alternateType := func() {
		if expectedType == "connector" {
			expectedType = "cable/arrow"
		} else {
			expectedType = "connector"
		}
	}

	for _, connectionSetVal := range connectionSets {
		connectionSet, ok := connectionSetVal.([]any)
		if !ok {
			continue
		}

		var connectioncount []int
		for _, entry := range connectionSet {
			switch e := entry.(type) {
			case []any:
				connectioncount = append(connectioncount, len(e))
			case *utils.OrderedMap:
				connectioncount = append(connectioncount, len(utils.Expand(e.First().Value)))
			}
		}
		hasCount := false
		for _, c := range connectioncount {
			if c != 0 {
				hasCount = true
				break
			}
		}
		if !hasCount {
			connectioncount = []int{1}
		}
		first := connectioncount[0]
		for _, c := range connectioncount {
			if c != first {
				panic(fmt.Errorf("All items in connection set must reference the same number of connections"))
			}
		}
		count := first

		for index, entry := range connectionSet {
			if s, ok := entry.(string); ok {
				expanded := make([]any, count)
				for i := 0; i < count; i++ {
					expanded[i] = s
				}
				connectionSet[index] = expanded
			}
		}

		for index, entry := range connectionSet {
			switch e := entry.(type) {
			case []any:
				for subindex, item := range e {
					_, des := resolveDesignator(utils.PyStr(item), templateSeparator)
					e[subindex] = des
				}
			case *utils.OrderedMap:
				kv := e.First()
				_, des := resolveDesignator(kv.Key, templateSeparator)
				nm := utils.NewOrderedMap()
				nm.Set(des, kv.Value)
				connectionSet[index] = nm
			}
		}

		for index, entry := range connectionSet {
			switch e := entry.(type) {
			case []any:
				var newList []any
				for _, des := range e {
					nm := utils.NewOrderedMap()
					nm.Set(utils.PyStr(des), 1)
					newList = append(newList, nm)
				}
				connectionSet[index] = newList
			case *utils.OrderedMap:
				kv := e.First()
				pinlist := utils.Expand(kv.Value)
				var newList []any
				for _, pin := range pinlist {
					nm := utils.NewOrderedMap()
					nm.Set(kv.Key, pin)
					newList = append(newList, nm)
				}
				connectionSet[index] = newList
			}
		}

		expectedType = ""
		for _, entry := range connectionSet {
			for _, item := range entry.([]any) {
				m := item.(*utils.OrderedMap)
				designator := m.First().Key
				template := designatorsAndTemplates[designator]
				if _, ok := h.ConnectorByName(designator); ok {
					checkType(designator, template, "connector")
				} else if t, ok := templateConnectors.Get(template); ok {
					checkType(designator, template, "connector")
					h.AddConnector(designator, t.(*utils.OrderedMap))
				} else if _, ok := h.CableByName(designator); ok {
					checkType(designator, template, "cable/arrow")
				} else if t, ok := templateCables.Get(template); ok {
					checkType(designator, template, "cable/arrow")
					h.AddCable(designator, t.(*utils.OrderedMap))
				} else if utils.IsArrow(designator) {
					checkType(designator, template, "cable/arrow")
				} else {
					panic(fmt.Errorf("%s is an unknown template/designator/arrow.", template))
				}
			}
			alternateType()
		}

		transposed := make([][]any, count)
		for _, entry := range connectionSet {
			inner := entry.([]any)
			for pinIdx, item := range inner {
				transposed[pinIdx] = append(transposed[pinIdx], item)
			}
		}

		for indexEntry, entry := range transposed {
			for indexItem, item := range entry {
				m := item.(*utils.OrderedMap)
				designator := m.First().Key
				if _, ok := h.CableByName(designator); ok {
					var fromName string
					var fromPin any
					if indexItem == 0 {
						fromName, fromPin = "", nil
					} else {
						kv := entry[indexItem-1].(*utils.OrderedMap).First()
						fromName, fromPin = kv.Key, kv.Value
					}
					viaName := designator
					viaPin := m.First().Value
					var toName string
					var toPin any
					if indexItem == len(entry)-1 {
						toName, toPin = "", nil
					} else {
						kv := entry[indexItem+1].(*utils.OrderedMap).First()
						toName, toPin = kv.Key, kv.Value
					}
					h.Connect(fromName, fromPin, viaName, viaPin, toName, toPin)
				} else if utils.IsArrow(designator) {
					if indexItem == 0 {
						panic(fmt.Errorf("An arrow cannot be at the start of a connection set"))
					}
					if indexItem == len(entry)-1 {
						panic(fmt.Errorf("An arrow cannot be at the end of a connection set"))
					}
					kvFrom := entry[indexItem-1].(*utils.OrderedMap).First()
					kvTo := entry[indexItem+1].(*utils.OrderedMap).First()
					fromName, fromPin := kvFrom.Key, kvFrom.Value
					toName, toPin := kvTo.Key, kvTo.Value
					if strings.Contains(designator, "-") {
						h.AddMatePin(fromName, fromPin, toName, toPin, designator)
					} else if strings.Contains(designator, "=") && indexEntry == 0 {
						h.AddMateComponent(fromName, toName, designator)
					}
				}
			}
		}
	}

	var proposed []string
	proposed = append(proposed, templateConnectors.Keys()...)
	proposed = append(proposed, templateCables.Keys()...)
	used := map[string]bool{}
	for _, t := range designatorsAndTemplates {
		used[t] = true
	}
	var forgotten []string
	for _, c := range proposed {
		if !used[c] {
			forgotten = append(forgotten, c)
		}
	}
	if len(forgotten) > 0 {
		fmt.Println("Warning: The following components are not referenced in any connection set:")
		fmt.Println(strings.Join(forgotten, ", "))
	}
}
