// wgo - Go port of WireViz.
//
// Copyright (C) 2026 the wgo contributors.
// Based on WireViz (https://github.com/wireviz/WireViz), copyright its
// respective contributors.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

package parser_test

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
	"unicode/utf8"

	"github.com/dmundt/wgo/pkg/parser"
	"github.com/dmundt/wgo/pkg/utils"
)

// TestGoldenOutputs runs every example YAML through the parser and compares
// each output file byte-for-byte with the golden outputs in testdata/golden,
// which were generated by the reference WireViz (0.4.1) + graphviz (0.21).
func TestGoldenOutputs(t *testing.T) {
	root := filepath.Join("..", "..")
	dataDir := filepath.Join(root, "testdata")
	inputs, err := filepath.Glob(filepath.Join(dataDir, "*.yml"))
	if err != nil {
		t.Fatal(err)
	}
	if len(inputs) == 0 {
		t.Fatal("no example inputs found in testdata")
	}

	formats := []string{"gv", "tsv"}
	extList := []string{"gv", "bom.tsv"}
	if _, err := exec.LookPath("dot"); err == nil {
		formats = append(formats, "svg", "png", "html")
		extList = append(extList, "svg", "png", "html")
	}

	tmp := t.TempDir()
	failures := 0
	for _, in := range inputs {
		name := strings.TrimSuffix(filepath.Base(in), filepath.Ext(in))
		input, err := os.ReadFile(in)
		if err != nil {
			t.Fatal(err)
		}
		outDir := filepath.Join(tmp, name)
		if err := os.MkdirAll(outDir, 0o755); err != nil {
			t.Fatal(err)
		}
		err = parser.Run(string(input), in, outDir, name, formats, []string{filepath.Dir(in)})
		if err != nil {
			t.Errorf("%s: parser error: %v", name, err)
			failures++
			continue
		}
		for _, ext := range extList {
			want := filepath.Join(dataDir, "golden", name+"."+ext)
			got := filepath.Join(outDir, name+"."+ext)
			wb, err := os.ReadFile(want)
			if err != nil {
				continue // golden not present for this format
			}
			gb, err := os.ReadFile(got)
			if err != nil {
				t.Errorf("%s.%s: missing output: %v", name, ext, err)
				failures++
				continue
			}
			if ext == "png" {
				// PNG is binary: compare byte-for-byte.
				if !bytes.Equal(wb, gb) {
					t.Errorf("%s.%s: output differs from golden", name, ext)
					failures++
				}
				continue
			}
			// Text formats: line endings are platform-dependent (the port
			// follows Python's text-mode writes: CRLF on Windows, LF on
			// Linux/macOS), and image source paths are absolute and
			// machine-dependent. Normalize both sides before comparing.
			if !bytes.Equal(normalizeText(wb, dataDir), normalizeText(gb, dataDir)) {
				t.Errorf("%s.%s: output differs from golden", name, ext)
				failures++
			}
		}
	}
	if failures > 0 {
		t.Fatalf("%d output mismatches", failures)
	}
}

// imagePathRe matches an absolute image source path ending in
// testdata/resources/<file>.
var imagePathRe = regexp.MustCompile(`[^"<>\s]*testdata[\\/]resources[\\/]([^"<>\s]*)`)

// normalizeText makes text outputs comparable across platforms by using
// universal newlines and by rewriting image paths to the current testdata dir.
func normalizeText(b []byte, dataDir string) []byte {
	b = bytes.ReplaceAll(b, []byte("\r\n"), []byte("\n"))
	sep := string(filepath.Separator)
	b = imagePathRe.ReplaceAll(b, []byte(dataDir+sep+"resources"+sep+"$1"))
	return b
}

// TestSourceFileEncoding guards against editors re-encoding source files
// (UTF-8 BOM insertion or Latin-1 -> UTF-8 double-encoding), which silently
// corrupts non-ASCII literals such as the mm2 -> mm² unit.
func TestSourceFileEncoding(t *testing.T) {
	root := filepath.Join("..", "..")
	var check func(path string) error
	check = func(path string) error {
		info, err := os.Lstat(path)
		if err != nil {
			return err
		}
		if info.IsDir() {
			if path == filepath.Join(root, ".git") {
				return nil
			}
			entries, err := os.ReadDir(path)
			if err != nil {
				return err
			}
			for _, e := range entries {
				if err := check(filepath.Join(path, e.Name())); err != nil {
					return err
				}
			}
			return nil
		}
		ext := strings.ToLower(filepath.Ext(path))
		switch ext {
		case ".go", ".yml", ".yaml", ".md", ".html":
		default:
			return nil // skip binaries and other formats
		}
		b, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if bytes.HasPrefix(b, []byte{0xEF, 0xBB, 0xBF}) {
			t.Errorf("%s: UTF-8 BOM present", filepath.ToSlash(path))
		}
		if !utf8.Valid(b) {
			t.Errorf("%s: invalid UTF-8", filepath.ToSlash(path))
		}
		if bytes.Contains(b, []byte("\xC3\x82\xC2\xB2")) {
			t.Errorf("%s: double-encoded 'mm²' literal", filepath.ToSlash(path))
		}
		return nil
	}
	for _, dir := range []string{"cmd", "pkg"} {
		if err := check(filepath.Join(root, dir)); err != nil {
			t.Fatal(err)
		}
	}
}

// TestYamlScalarResolution checks pyyaml-compatible scalar type resolution.
func TestYamlScalarResolution(t *testing.T) {
	cases := map[string]any{
		"a: 08500030\n": "08500030",
		"a: 0123\n":     83,
		"a: 0x1F\n":     31,
		"a: 1e3\n":      "1e3",
		"a: 1.5\n":      1.5,
		"a: .5\n":       0.5,
		"a: yes\n":      true,
		"a: 'yes'\n":    "yes",
		"a: null\n":     nil,
		"a: 1_000\n":    1000,
		"a: true\n":     true,
		"a: 0.25 mm2\n": "0.25 mm2",
	}
	for yml, want := range cases {
		root, err := parser.LoadYAML([]byte(yml))
		if err != nil {
			t.Fatalf("%q: %v", yml, err)
		}
		om, ok := root.(*utils.OrderedMap)
		if !ok {
			t.Fatalf("%q: not an ordered map", yml)
		}
		got, _ := om.Get("a")
		if !scalarEqual(got, want) {
			t.Errorf("%q: got %#v (%T), want %#v (%T)", yml, got, got, want, want)
		}
	}
}

func TestMergeKeys(t *testing.T) {
	yml := "base: &b {type: Molex KK 254, subtype: female}\n" +
		"connectors:\n  X1:\n    <<: *b\n    pinlabels: [GND, VCC]\n  X2:\n    <<: *b\n"
	root, err := parser.LoadYAML([]byte(yml))
	if err != nil {
		t.Fatal(err)
	}
	om := root.(*utils.OrderedMap)
	conns, _ := om.Get("connectors")
	cm := conns.(*utils.OrderedMap)
	x1, _ := cm.Get("X1")
	x1m := x1.(*utils.OrderedMap)
	gotType, _ := x1m.Get("type")
	if gotType != "Molex KK 254" {
		t.Errorf("merge key not applied: %#v", gotType)
	}
	if _, ok := x1m.Get("subtype"); !ok {
		t.Errorf("merged subtype missing")
	}
	if _, ok := x1m.Get("pinlabels"); !ok {
		t.Errorf("explicit pinlabels missing")
	}
	x2, _ := cm.Get("X2")
	x2m := x2.(*utils.OrderedMap)
	if _, ok := x2m.Get("type"); !ok {
		t.Errorf("X2 merged type missing")
	}
}

func scalarEqual(a, b any) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	as := fmt.Sprintf("%v", a)
	bs := fmt.Sprintf("%v", b)
	return as == bs
}
